// <auto-generated />
namespace SAP_GCL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DocumentError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocumentError));
        
        string IMigrationMetadata.Id
        {
            get { return "201712211455411_DocumentError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
